import type { Metadata } from "next";
import { Roboto, Lobster } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import FaceBookMsg from "@/components/faceBookMsg";

// const roboto_init = Roboto({
//   subsets: ["latin"],
//   weight: ["100", "300", "500"],
//   variable: "--font-roboto"
// });
// const agbalumo_init = Agbalumo({
//   subsets: ["latin"],
//   weight: ["400"],
//   variable: "--font-agbalumo"
// });
// const lobster_init = Lobster({
//   subsets: ["latin"],
//   weight: ["400"],
//   variable: "--font-lobster"
// });

export const metadata: Metadata = {
  title: "Larissa Restaurants",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        {children}
        <Footer />
        <FaceBookMsg /></body>
    </html>
  );
}
